### ISSUE TITLE
Data Preparation:

### ISSUE THREAD

**Issue by johndpope** [johndpope/Emote-hack#1]
Download the required datasets. Write data loaders and preprocessors as per the paper's specifications.

150 million images.
250 hours of video

**Comment by johndpope** [comment]
let's use this
https://academictorrents.com/details/843b5adb0358124d388c4e9836654c246b988ff4

**Comment by johndpope** [comment]
training code on celebhq-v dataset (not using stable diffusion under the hood)
https://github.com/JialeTao/MRFA

**Comment by CHK-0000** [comment]
Does the 150 million image data used for EMO require images with only human faces? Or do you need images of faces from multiple angles? If not, please let me know. Thank you.

**Comment by johndpope** [comment]
using the 40gb torrent we have lots of mp4s + we have Dataset - we can load the videos + audio - get the frames / audio features.

https://github.com/johndpope/Emote-hack/blob/main/Net.py#L1004

see training stage 1/2/3
