### ISSUE TITLE
1.5 billion image data questions

### ISSUE THREAD

**Issue by CHK-0000** [johndpope/Emote-hack#10]
Does the 150 million image data used for EMO require images with only human faces? Or do you need images of faces from multiple angles? If not, please let me know. Thank you.

**Comment by johndpope** [comment]
The reference net takes first frame then random frame from video - this is to help keep character consistent across generation of many frames. See my notes on attention under junk.

**Comment by CHK-0000** [comment]
Is the 150 million image data just human faces, and if so, are they images
of faces taken from multiple angles?

2024년 3월 14일 (목) 오후 3:46, John D. Pope ***@***.***>님이 작성:

**Comment by johndpope** [comment]
i don't see this in the paper - https://arxiv.org/html/2402.17485v1
there's no mention of this in their training strategies.

**Comment by CHK-0000** [comment]
In the EMO GitHub repository for the current implementation, there are four
training codes: train_stage_0.py, train_stage_1.py, train_stage_2.py, and
train_stage_3.py. Are they available for use now, and if so, which one
should I use?

2024년 3월 14일 (목) 오후 4:13, John D. Pope ***@***.***>님이 작성:
