### ISSUE TITLE
Thanks and Status Update

### ISSUE THREAD

**Issue by fire17** [johndpope/Emote-hack#14]
Hi there! glad I found this repo :)
Wanted to come to say thanks and also to ask how's progress coming?

We're you able to find other repos or people that are also working on this?
Have you found more people experienced in this background to collab with?

Sadly I'm not one of the above, but still here to show support :)

I can't wait till we we have these incredible capabilities out in the open. Emote is one of the strongest demos , it's almost flawless.
Imagine soon we will have foss Sora+Emo+Boximator that would be insane, and even without Sora, Realtime+Whisper+11Labs 
And you got a "facetime" capable ai agent

Hope to see it this year,
Let me know your take and which other things you've seen that you're excited for!
Thanks a lot and all the best!

**Comment by johndpope** [comment]
Thanks for the encouragement Tami. It's an exciting space.
There is a few repos i draw your attention to that you might be interested in

https://github.com/OpenTalker/SadTalker
https://github.com/Shaunwei/RealChar
