### ISSUE TITLE
Looks similar to DINet

### ISSUE THREAD

**Issue by Inferencer** [johndpope/Emote-hack#15]
Looks like a similar process to DINet and your implementation on more along the lines of DINET Optimized which is a re implementation of Dinet using wav2vec rather than deepspeech, what results are you trying to produce that would be different to these repos?

**Comment by johndpope** [comment]
Thanks for pointing this out. The audio attention stuff / training / weights in that repo is missing. 
I did some deep diving today - 
https://github.com/johndpope/Emote-hack/commit/f80d57e9be68fc7f078052a7ea37ad823ee4f792

I create some mock sounds (using audio craft)  / graphics (see junk/AudioAttention)  in  in an attempt to get more intuition of the attention mechanism.  It's not quite there. I want to be able to give a sound - and get back a generated image.
resnet has some classification layer that gets ripped out - I'm not sure that's the best image feature representation here either.
I'm wondering if wiring up tensorboard will help.

**Comment by johndpope** [comment]
I started pulling apart - animatediff with Claude 3 - it says it can get 100x performance improvement with 4 lines of code change -  https://github.com/guoyww/AnimateDiff/issues/308
