### ISSUE TITLE
Calling out coders to contribute to implement EMOTE

### ISSUE THREAD

**Issue by johndpope** [johndpope/Emote-hack#18]
https://github.com/johndpope/Emote-hack

I understand you developers have forked and worked on the [animateanyone](https://github.com/MooreThreads/Moore-AnimateAnyone/network) codebase.

@supplepentan,@Bismuth209,@zsxkib,@Pipazoul,@sdbds,@Shubham123A,@npjd
@JinJiangHuang,@jameynakama,@candywrap,@eltociear
@INF800,@cocktailpeanut,@MooreThreads
@hDluffy,@daocodedao,@lixunsong,@superzhangmch
@itrushkin,@Chenyu-Inspirai,@liuwenran,@AnnnnnieZhang
@robonich,@P-Chao,@thigazholi,@qingyuanxingsi
@chucklien,@donlee1,@MoonEese

I am willing to sponsor a subscription of chatgpt 4 OR claude 3 for a month - for anyone(above) that is willing to spend any time to help get the training code over the line. There's 3 stages. I drafted these - but it's not there.

Successful PRs that get merged - I'll extend for a year. 
You have to understand PR code you're submitting. I don't expect you to code anything - just use ai to do it -

**Comment by hedada-hc** [comment]
how to help you

**Comment by hedada-hc** [comment]
Has the project encountered any difficulties recently? How is the progress? Can you show some samples?

**Comment by johndpope** [comment]
going to push for this solution - https://github.com/johndpope/Emote-hack/issues/23
