### ISSUE TITLE
check this out

### ISSUE THREAD

**Issue by Inferencer** [johndpope/Emote-hack#22]
https://yudeng.github.io/Portrait4D-v2/

**Comment by johndpope** [comment]
i got chatgpt to spit torch code - may give another with claude. you want to be specific - 
next time I may impose it to use stable diffusion process (though im yet to validate ai can do this).
https://chat.openai.com/share/9cdf6225-ca86-4945-9886-ec87bf5176b0

I need to wire up the training music to this Adobe research paper "I made" / claude ai spat out.
https://github.com/johndpope/musiccontrolnet
