### ISSUE TITLE
Hi，how is the progress？

### ISSUE THREAD

**Issue by jeffreyking23** [johndpope/Emote-hack#33]
same as title

**Comment by johndpope** [comment]
this code dropped some weeks back - https://github.com/Zejun-Yang/AniPortrait  
it just needs the motion buckets / face locator. 


separate to that - this repo dropped their training code
https://github.com/MStypulkowski/diffused-heads/tree/train

this particular fuction was referenced in EMO - 
![Screenshot from 2024-04-12 08-10-43](https://github.com/johndpope/Emote-hack/assets/289994/9ee5efd4-cc22-4b18-9423-ca5149f8727b)

I did a quick look to look for this concatenation - but it's not so obvious to me how it is done.

**Comment by johndpope** [comment]
this code base is dropping in july https://github.com/neeek2303/EMOPortraits

**Comment by johndpope** [comment]
i had some success with this paper - 
https://github.com/johndpope/MegaPortrait-hack/issues/36
needs more compute -
i switch to attempting to integrate into VASA https://github.com/johndpope/VASA-1-hack/tree/MegaPortraits
