### ISSUE TITLE
Decord + cuda12 

### ISSUE THREAD

**Issue by johndpope** [johndpope/Emote-hack#9]
```python 
        decord.bridge.set_bridge('torch')  # Optional: This line sets decord to directly output PyTorch tensors.
        self.ctx = decord.cpu()
```

setting to gpu will fail if decord was installed using pip.
have to manually build.

decord + cuda
https://github.com/zhanwenchen/decord/tree/f4d56232a82cfa0280ea467ad7f294c88ce9f01c
 cmake .. -DUSE_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc 
echo "PYTHONPATH=$PYTHONPATH:$pwd"  >> ~/.zshrc

**Comment by nitinmukesh** [comment]
Awesome. We can't waiting to use this.
Thanks for your hard work.

**Comment by johndpope** [comment]
because the videos need to be occasionally resized - doing everything exclusively in gpu land can wait.
